import type { Metadata } from "next";
import { Montserrat } from 'next/font/google'
import "./globals.css";
import "./variables.scss";
import "./style.scss";
import Link from "next/link";
import Image from "next/image";

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  weight: ['400','500','600','700','800'],
  display: "swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body>
        <div className="fixed top-0 left-0 w-full z-50 bg-white">
        <header className="z-50 bg-white container flex items-center justify-between">
            <Link href="/" className="cursor-pointer">
              <Image
                src="/kompunity logo.svg"
                alt="Next.js logo"
                width={60}
                height={35}
                priority
              />
            </Link>

            <nav className="py-4">
              <div className="space-x-6">
                <Link href="/">
                  main
                </Link>
                <Link href="/about" className="hover:text-gray-300">
                  about
                </Link>
                <Link href="/contacts" className="hover:text-gray-300">
                  contacts
                </Link>
                <Link href="/blog" className="hover:text-gray-300">
                  blog
                </Link>
                <Link href="/reviews" className="hover:text-gray-300">
                  reviews
                </Link>
              </div>
            </nav>
        </header>
        </div>
        

        <main className="mt-[56px]">

          {children}

        </main>

        <footer className="flex w-full flex-wrap container">
          <div className="w-[30%]">
            <h3 className="text-[36px] font-bold">
              KOMPUNITY
            </h3>
            <h4 className="text-[22px] font-semibold">
              ООО "KompUnity" - это динамично развивающаяся компания, созданная успешными профессионалами в сфере оптовых продаж компьютерной и офисной техники.
            </h4>
          </div>
          <div className="w-[30%] text-center">
            <h3 className="text-[40px] font-semibold">
              Адрес
            </h3>
            <ul className="font-medium">
              <li>
                <a href="https://yandex.by/maps/org/kompyuniti/116356714415/?ll=27.516313%2C53.923238&z=17">
                  Сапёров 5, Минск
                </a>
              </li>
            </ul>
            <ul className="font-medium">
              <li>
                <a href="mailto:kompunity.by@gmail.com">
                  kompunity.by@gmail.com
                </a>
              </li>
            </ul>
          </div>
          <div className="w-[30%] text-center">
            <h3 className="text-[40px] font-semibold">Контакты</h3>
            <ul className="font-medium">
              <div>
                <li>А1 44 703 97 07</li>
                <li>МТС 33 636 97 07</li>
                <li>Гор 17 307 97 07</li>
              </div>
            </ul>
          </div>
          <div className="w-full text-center">
            <span>
              OOO “КомпЮнити” Адрес: г. Минск, 220035, ул. Сапёров, д. 5-1, пом. 204 Банковские реквизиты: р/с BY 14 PJCB 3012 0747041000000 933 (BYN) ОАО “Приорбанк” г. Минск, БИК PJCBBY2X УНП 193633364 На основании Устава
            </span>
          </div>
        </footer>
      </body>
    </html>
  );
}
