import type { Metadata } from "next";
import { Montserrat } from 'next/font/google'
import "./globals.css";
import "./variables.scss";
import "./style.scss";
import Link from "next/link";
import Image from "next/image";

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  weight: ['400','500','600','700','800'],
  display: "swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body>
        <head>
          <style>
            {'@layer properties{@supports (((-webkit-hyphens:none)) and (not (margin-trim:inline))) or ((-moz-orient:inline) and (not (color:rgb(from red r g b)))){*,:after,:before{--tw-translate-x:0;--tw-translate-y:0;--tw-translate-z:0;--tw-rotate-x:initial;--tw-rotate-y:initial;--tw-rotate-z:initial;--tw-skew-x:initial;--tw-skew-y:initial;--tw-space-y-reverse:0;--tw-space-x-reverse:0;--tw-border-style:solid;--tw-leading:initial;--tw-font-weight:initial;--tw-shadow:0 0 #0000;--tw-shadow-color:initial;--tw-shadow-alpha:100%;--tw-inset-shadow:0 0 #0000;--tw-inset-shadow-color:initial;--tw-inset-shadow-alpha:100%;--tw-ring-color:initial;--tw-ring-shadow:0 0 #0000;--tw-inset-ring-color:initial;--tw-inset-ring-shadow:0 0 #0000;--tw-ring-inset:initial;--tw-ring-offset-width:0px;--tw-ring-offset-color:#fff;--tw-ring-offset-shadow:0 0 #0000;--tw-blur:initial;--tw-brightness:initial;--tw-contrast:initial;--tw-grayscale:initial;--tw-hue-rotate:initial;--tw-invert:initial;--tw-opacity:initial;--tw-saturate:initial;--tw-sepia:initial;--tw-drop-shadow:initial;--tw-drop-shadow-color:initial;--tw-drop-shadow-alpha:100%;--tw-drop-shadow-size:initial;--tw-backdrop-blur:initial;--tw-backdrop-brightness:initial;--tw-backdrop-contrast:initial;--tw-backdrop-grayscale:initial;--tw-backdrop-hue-rotate:initial;--tw-backdrop-invert:initial;--tw-backdrop-opacity:initial;--tw-backdrop-saturate:initial;--tw-backdrop-sepia:initial;--tw-ease:initial}}}@layer theme{:root{--font-sans:ui-sans-serif,system-ui,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";--font-mono:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;--color-red-100:oklch(93.6% .032 17.717);--color-red-500:oklch(63.7% .237 25.331);--color-red-700:oklch(50.5% .213 27.518);--color-red-800:oklch(44.4% .177 26.899);--color-yellow-400:oklch(85.2% .199 91.936);--color-green-100:oklch(96.2% .044 156.743);--color-green-400:oklch(79.2% .209 151.711);--color-green-700:oklch(52.7% .154 150.069);--color-green-800:oklch(44.8% .119 151.328);--color-blue-600:oklch(54.6% .245 262.881);--color-blue-700:oklch(48.8% .243 264.376);--color-gray-100:oklch(96.7% .003 264.542);--color-gray-200:oklch(92.8% .006 264.531);--color-gray-300:oklch(87.2% .01 258.338);--color-gray-400:oklch(70.7% .022 261.325);--color-gray-500:oklch(55.1% .027 264.364);--color-gray-600:oklch(44.6% .03 256.802);--color-gray-700:oklch(37.3% .034 259.733);--color-gray-900:oklch(21% .034 264.665);--color-black:#000;--color-white:#fff;--spacing:.25rem;--container-md:28rem;--text-sm:.875rem;--text-sm--line-height:calc(1.25/.875);--text-lg:1.125rem;--text-lg--line-height:calc(1.75/1.125);--text-xl:1.25rem;--text-xl--line-height:calc(1.75/1.25);--text-2xl:1.5rem;--text-2xl--line-height:calc(2/1.5);--text-3xl:1.875rem;--text-3xl--line-height:calc(2.25/1.875);--text-4xl:2.25rem;--text-4xl--line-height:calc(2.5/2.25);--text-7xl:4.5rem;--text-7xl--line-height:1;--font-weight-medium:500;--font-weight-semibold:600;--font-weight-bold:700;--leading-relaxed:1.625;--radius-md:.375rem;--radius-lg:.5rem;--radius-xl:.75rem;--drop-shadow-lg:0 4px 4px #00000026;--ease-in-out:cubic-bezier(.4,0,.2,1);--animate-spin:spin 1s linear infinite;--blur-sm:8px;--default-transition-duration:.15s;--default-transition-timing-function:cubic-bezier(.4,0,.2,1);--default-font-family:var(--font-sans);--default-mono-font-family:var(--font-mono)}}@layer base{*,:after,:before{box-sizing:border-box;border:0 solid;margin:0;padding:0}html{-webkit-text-size-adjust:100%;tab-size:4;line-height:1.5;font-family:var(--default-font-family,ui-sans-serif,system-ui,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji");font-feature-settings:var(--default-font-feature-settings,normal);font-variation-settings:var(--default-font-variation-settings,normal);-webkit-tap-highlight-color:transparent}h1,h2,h3,h4,h5{font-size:inherit;font-weight:inherit}a{color:inherit;-webkit-text-decoration:inherit;text-decoration:inherit}ul{list-style:none}canvas,iframe,img,svg{vertical-align:middle;display:block}img{max-width:100%;height:auto}button,input,textarea{font:inherit;font-feature-settings:inherit;font-variation-settings:inherit;letter-spacing:inherit;color:inherit;opacity:1;background-color:#0000;border-radius:0}textarea{resize:vertical}button,input:where([type=button],[type=reset],[type=submit]){appearance:button}}@layer components;@layer utilities{.pointer-events-auto{pointer-events:auto}.pointer-events-none{pointer-events:none}.absolute{position:absolute}.fixed{position:fixed}.relative{position:relative}.inset-0{inset:calc(var(--spacing)*0)}.top-0{top:calc(var(--spacing)*0)}.top-1\/2{top:50%}.bottom-8{bottom:calc(var(--spacing)*8)}.left-0{left:calc(var(--spacing)*0)}.left-1\/2{left:50%}.z-0{z-index:0}.z-2{z-index:2}.z-10{z-index:10}.z-50{z-index:50}.container{width:100%}@media (min-width:40rem){.container{max-width:40rem}}@media (min-width:48rem){.container{max-width:48rem}}@media (min-width:64rem){.container{max-width:64rem}}@media (min-width:80rem){.container{max-width:80rem}}@media (min-width:96rem){.container{max-width:96rem}}.mt-8{margin-top:calc(var(--spacing)*8)}.mt-\[10px\]{margin-top:10px}.mt-\[20px\]{margin-top:20px}.mt-\[56px\]{margin-top:56px}.mr-\[30px\]{margin-right:30px}.mb-6{margin-bottom:calc(var(--spacing)*6)}.mb-14{margin-bottom:calc(var(--spacing)*14)}.mb-\[100px\]{margin-bottom:100px}.ml-\[20px\]{margin-left:20px}.flex{display:flex}.h-\[100px\]{height:100px}.h-\[650px\]{height:650px}.h-full{height:100%}.w-\[30\%\]{width:30%}.w-\[49\%\]{width:49%}.w-\[70\%\]{width:70%}.w-\[100\%\]{width:100%}.w-\[160px\]{width:160px}.w-full{width:100%}.-translate-x-1\/2{--tw-translate-x:calc(calc(1/2*100%)*-1)}.-translate-x-1\/2,.-translate-y-1\/2{translate:var(--tw-translate-x)var(--tw-translate-y)}.-translate-y-1\/2{--tw-translate-y:calc(calc(1/2*100%)*-1)}.transform{transform:var(--tw-rotate-x,)var(--tw-rotate-y,)var(--tw-rotate-z,)var(--tw-skew-x,)var(--tw-skew-y,)}.cursor-pointer{cursor:pointer}.touch-none{touch-action:none}.flex-col{flex-direction:column}.flex-wrap{flex-wrap:wrap}.items-center{align-items:center}.items-start{align-items:flex-start}.justify-between{justify-content:space-between}.justify-center{justify-content:center}.gap-\[2\%\]{gap:2%}.gap-\[5px\]{gap:5px}.gap-\[20px\]{gap:20px}.overflow-hidden{overflow:hidden}.rounded-\[30px\]{border-radius:30px}.rounded-xl{border-radius:var(--radius-xl)}.bg-black{background-color:var(--color-black)}.bg-gray-200{background-color:var(--color-gray-200)}.bg-green-400{background-color:var(--color-green-400)}.bg-white{background-color:var(--color-white)}.object-cover{object-fit:cover}.p-\[20px\]{padding:20px}.py-4{padding-block:calc(var(--spacing)*4)}.pr-10{padding-right:calc(var(--spacing)*10)}.text-center{text-align:center}.text-4xl{font-size:var(--text-4xl);line-height:var(--tw-leading,var(--text-4xl--line-height))}.text-7xl{font-size:var(--text-7xl);line-height:var(--tw-leading,var(--text-7xl--line-height))}.text-\[22px\]{font-size:22px}.text-\[36px\]{font-size:36px}.text-\[40px\]{font-size:40px}.font-bold{--tw-font-weight:var(--font-weight-bold);font-weight:var(--font-weight-bold)}.font-medium{--tw-font-weight:var(--font-weight-medium);font-weight:var(--font-weight-medium)}.font-semibold{--tw-font-weight:var(--font-weight-semibold);font-weight:var(--font-weight-semibold)}.whitespace-nowrap{white-space:nowrap}.text-white{color:var(--color-white)}.italic{font-style:italic}.opacity-25{opacity:.25}.ring{--tw-ring-shadow:var(--tw-ring-inset,)0 0 0 calc(1px + var(--tw-ring-offset-width))var(--tw-ring-color,currentcolor);box-shadow:var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)}.drop-shadow-lg{filter:var(--tw-blur,)var(--tw-brightness,)var(--tw-contrast,)var(--tw-grayscale,)var(--tw-hue-rotate,)var(--tw-invert,)var(--tw-saturate,)var(--tw-sepia,)var(--tw-drop-shadow,)}.drop-shadow-lg{--tw-drop-shadow-size:drop-shadow(0 4px 4px var(--tw-drop-shadow-color,#00000026));--tw-drop-shadow:drop-shadow(var(--drop-shadow-lg))}.outline-none{--tw-outline-style:none;outline-style:none}.select-none{-webkit-user-select:none;user-select:none}@media (hover:hover){.hover\:text-gray-300:hover{color:var(--color-gray-300)}}}.figure-color{margin:0;display:inline-block;position:relative}.figure-color:after,.figure-color:before{content:"";transform-origin:100%;background:linear-gradient(90deg,#50f,#00ff1a);width:100%;height:2px;position:absolute;bottom:-5px;left:0;transform:scaleX(0)}.figure-color:after{transform-origin:0}.figure-color:before{transform-origin:100%;top:-5px}.figure-color:hover:after,.figure-color:hover:before{transform:scaleX(1)}@property --tw-translate-x{syntax:"*";inherits:false;initial-value:0}@property --tw-translate-y{syntax:"*";inherits:false;initial-value:0}@property --tw-translate-z{syntax:"*";inherits:false;initial-value:0}@property --tw-rotate-x{syntax:"*";inherits:false}@property --tw-rotate-y{syntax:"*";inherits:false}@property --tw-rotate-z{syntax:"*";inherits:false}@property --tw-skew-x{syntax:"*";inherits:false}@property --tw-skew-y{syntax:"*";inherits:false}@property --tw-space-y-reverse{syntax:"*";inherits:false;initial-value:0}@property --tw-space-x-reverse{syntax:"*";inherits:false;initial-value:0}@property --tw-border-style{syntax:"*";inherits:false;initial-value:solid}@property --tw-leading{syntax:"*";inherits:false}@property --tw-font-weight{syntax:"*";inherits:false}@property --tw-shadow{syntax:"*";inherits:false;initial-value:0 0 #0000}@property --tw-shadow-color{syntax:"*";inherits:false}@property --tw-shadow-alpha{syntax:"<percentage>";inherits:false;initial-value:100%}@property --tw-inset-shadow{syntax:"*";inherits:false;initial-value:0 0 #0000}@property --tw-inset-shadow-color{syntax:"*";inherits:false}@property --tw-inset-shadow-alpha{syntax:"<percentage>";inherits:false;initial-value:100%}@property --tw-ring-color{syntax:"*";inherits:false}@property --tw-ring-shadow{syntax:"*";inherits:false;initial-value:0 0 #0000}@property --tw-inset-ring-color{syntax:"*";inherits:false}@property --tw-inset-ring-shadow{syntax:"*";inherits:false;initial-value:0 0 #0000}@property --tw-ring-inset{syntax:"*";inherits:false}@property --tw-ring-offset-width{syntax:"";inherits:false;initial-value:0}@property --tw-ring-offset-color{syntax:"*";inherits:false;initial-value:#fff}@property --tw-ring-offset-shadow{syntax:"*";inherits:false;initial-value:0 0 #0000}@property --tw-blur{syntax:"*";inherits:false}@property --tw-brightness{syntax:"*";inherits:false}@property --tw-contrast{syntax:"*";inherits:false}@property --tw-grayscale{syntax:"*";inherits:false}@property --tw-hue-rotate{syntax:"*";inherits:false}@property --tw-invert{syntax:"*";inherits:false}@property --tw-opacity{syntax:"*";inherits:false}@property --tw-saturate{syntax:"*";inherits:false}@property --tw-sepia{syntax:"*";inherits:false}@property --tw-drop-shadow{syntax:"*";inherits:false}@property --tw-drop-shadow-color{syntax:"*";inherits:false}@property --tw-drop-shadow-alpha{syntax:"<percentage>";inherits:false;initial-value:100%}@property --tw-drop-shadow-size{syntax:"*";inherits:false}@property --tw-backdrop-blur{syntax:"*";inherits:false}@property --tw-backdrop-brightness{syntax:"*";inherits:false}@property --tw-backdrop-contrast{syntax:"*";inherits:false}@property --tw-backdrop-grayscale{syntax:"*";inherits:false}@property --tw-backdrop-hue-rotate{syntax:"*";inherits:false}@property --tw-backdrop-invert{syntax:"*";inherits:false}@property --tw-backdrop-opacity{syntax:"*";inherits:false}@property --tw-backdrop-saturate{syntax:"*";inherits:false}@property --tw-backdrop-sepia{syntax:"*";inherits:false}@property --tw-ease{syntax:"*";inherits:false}:root{--container-width:1500px;--container-offset:16px;--min-viewport:320px;--max-viewport:1500px;--base-font-size:16px}.section__responsive-padding{padding-top:clamp(2.5rem,(100vw - 320px)/1180*(80 - 40) + 40px,5rem);padding-bottom:clamp(2.5rem,(100vw - 320px)/1180*(80 - 40) + 40px,5rem)}.h1__slider-title_responsive-font,.h2__slider-title_responsive-font{font-size:clamp(1rem,(100vw - 320px)/1180*(70 - 16) + 16px,4.375rem)}.h2__section-title_responsive-font{font-weight:700;font-size:clamp(1.25rem,(100vw - 320px)/1180*(40 - 20) + 20px,2.5rem);margin-top:clamp(1.25rem,(100vw - 320px)/1180*(40 - 20) + 20px,2.5rem);margin-bottom:clamp(1.25rem,(100vw - 320px)/1180*(40 - 20) + 20px,2.5rem)}.h3__section-title_responsive-font{font-size:clamp(.75rem,(100vw - 320px)/1180*(28 - 12) + 12px,1.75rem)}.li__section_responsive-font{font-size:clamp(.75rem,(100vw - 320px)/1180*(21 - 12) + 12px,1.3125rem)}.h4__category-section_responsive-font{font-size:clamp(1.125rem,(100vw - 320px)/1180*(30 - 18) + 18px,1.875rem);font-weight:600}.h5__category-section_responsive-font{font-size:clamp(.8125rem,(100vw - 320px)/1180*(20 - 13) + 13px,1.25rem);font-weight:600}.h4__advantages-section_responsive-font{font-size:clamp(1.0625rem,(100vw - 320px)/1180*(33 - 17) + 17px,2.0625rem);font-weight:600}.p__advantages-section_responsive-font{font-size:clamp(.8125rem,(100vw - 320px)/1180*(24 - 13) + 13px,1.5rem);font-weight:400}.buttons{text-align:center;border-radius:30px;position:relative}.buttons:after,.buttons:before{margin:0;padding:0}.blob-btn{z-index:1;position:relative;padding:20px 46px;text-align:center;text-transform:uppercase;color:#fff;font-size:16px;font-weight:700;background-color:rgba(0,0,0,0);outline:none;border:none;transition:color .5s;cursor:pointer;border-radius:30px}.blob-btn:before{z-index:1;left:0;top:0}.blob-btn:after,.blob-btn:before{content:"";position:absolute;width:100%;height:100%}.blob-btn:after{z-index:-2;left:3px;top:3px;transition:all .3s .2s;border-radius:30px}.blob-btn:hover{color:#fff;border-radius:30px}.blob-btn:hover:after{transition:all .3s;left:0;top:0;border-radius:30px}.blob-btn__inner{z-index:-1;overflow:hidden;position:absolute;left:0;top:0;width:100%;height:100%;border-radius:30px;background:linear-gradient(0deg,#5457c1,#449a8d)}.blob-btn__blobs{position:relative;display:block;height:100%;filter:url(#goo)}.blob-btn__blob{position:absolute;top:2px;width:25%;height:100%;background:#0588a9;border-radius:100%;transform:translate3d(0,150%,0) scale(1.9);transition:transform .45s}@supports(filter:url("#goo")){.blob-btn__blob{transform:translate3d(0,150%,0) scale(1.9)}}.blob-btn__blob:first-child{left:0;transition-delay:0s}.blob-btn__blob:nth-child(2){left:30%;transition-delay:.08s}.blob-btn__blob:nth-child(3){left:60%;transition-delay:.16s}.blob-btn__blob:nth-child(4){left:90%;transition-delay:.24s}.blob-btn:hover .blob-btn__blob{transform:translateZ(0) scale(1.9)}@supports(filter:url("#goo")){.blob-btn:hover .blob-btn__blob{transform:translateZ(0) scale(1.9)}}body{background-color:#fff;color:#000;font-size:var(--base-font-size)}.container{width:var(--container-width);padding-left:var(--container-offset);padding-right:var(--container-offset);margin:0 auto;max-width:100%}canvas{will-change:transform;transform:translateZ(0)}.category-section__images{display:flex;gap:15px;flex-wrap:wrap;justify-content:space-between}.category-section__images picture{position:relative;overflow:hidden;transition:border-radius 1.7s ease}.category-section__images picture:before{content:"";position:absolute;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0);z-index:1;pointer-events:none;border-radius:inherit;transition:background 1.25s;will-change:"transform, opacity"}.category-section__images picture:hover:before{background:rgba(0,0,0,.568627451)}.category-section__images picture:hover{border-bottom-right-radius:25%;border-top-left-radius:25%}.category-section__images picture img{width:100%;height:100%;object-fit:cover;transition:transform 1.1s;will-change:"transform"}.category-section__images picture:hover img{transform:scale(1.3)}.category-section__images picture div.category-text{position:absolute;top:50%;left:50%;transform:translate3d(-50%,-50%,0);display:flex;flex-direction:column;justify-content:center;text-align:center;z-index:2;color:#fff;line-height:15;transition:line-height 1.1s,opacity 1.1s;will-change:"transform, opacity"}.category-section__images picture div.category-text h4,.category-section__images picture div.category-text h5{cursor:pointer;opacity:0;transition:opacity 1.1s}.category-section__images picture:hover div.category-text{line-height:2}.category-section__images picture:hover div.category-text h4,.category-section__images picture:hover div.category-text h5{opacity:1}.category-image-main{width:100%}.category-image-main,.category-image-row{height:45vh;max-height:370px;min-height:200px}.category-image-row{width:calc((100% - 30px)/3)}.category-image-row-bottom{width:calc((100% - 15px)/2);height:45vh;max-height:370px;min-height:200px}.advantages__section{display:flex;flex-wrap:wrap;justify-content:space-between;gap:25px 0}.advantages__section .advantages__section-item{width:30%;display:flex;flex-direction:column;align-items:center;justify-content:start;will-change:"transform, opacity";transform:translateZ(0)}:root{--swiper-theme-color:#007aff}:root{--swiper-navigation-size:44px}.embla{max-width:100%;margin:auto;--slide-height:auto;--slide-spacing:1%;--slide-size:100%;--slide-spacing-sm:20px;--slide-size-sm:50%;--slide-spacing-lg:20px;--slide-size-lg:calc(100% / 5)}.embla-height{height:30vw;max-height:300px;min-height:150px}.embla__viewport{overflow:hidden}.embla__container{backface-visibility:hidden;display:flex;touch-action:pan-y pinch-zoom;margin-left:calc(var(--slide-spacing) * -1)}@media (min-width:750px){.embla__container{margin-left:calc(var(--slide-spacing-sm) * -1)}}@media (min-width:1200px){.embla__container{margin-left:calc(var(--slide-spacing-lg) * -1)}}.embla__slide{min-width:0;flex:0 0 var(--slide-size);padding-left:var(--slide-spacing)}@media (min-width:750px){.embla__slide{flex:0 0 var(--slide-size-sm);padding-left:var(--slide-spacing-sm)}}@media (min-width:1200px){.embla__slide{flex:0 0 var(--slide-size-lg);padding-left:var(--slide-spacing-lg)}}.arrow{opacity:0.3;transform:translateZ(0);marker-end:url(#arrowhead)}.arrow-1{animation:arrowPulse 10s infinite}.arrow-2{animation:arrowPulse 10s infinite 3.3s}.arrow-3{animation:arrowPulse 10s infinite 6.6s}@keyframes arrowPulse {0%{opacity:0.3}10%{opacity:0.5}20%{opacity:0.5}30%{opacity:0.3}100%{opacity:0.3}}'}
          </style>
        </head>
        <div className="fixed top-0 left-0 w-full z-50 bg-white">
        <header className="z-50 bg-white container flex items-center justify-between">
            <Link href="/" className="cursor-pointer">
              <Image
                src="/kompunity logo.svg"
                alt="Next.js logo"
                width={60}
                height={35}
                priority
              />
            </Link>

            <nav className="py-4">
              <div className="space-x-6">
                <Link href="/">
                  main
                </Link>
                <Link href="/about" className="hover:text-gray-300">
                  about
                </Link>
                <Link href="/contacts" className="hover:text-gray-300">
                  contacts
                </Link>
                <Link href="/blog" className="hover:text-gray-300">
                  blog
                </Link>
                <Link href="/reviews" className="hover:text-gray-300">
                  reviews
                </Link>
              </div>
            </nav>
        </header>
        </div>
        

        <main className="mt-[56px]">

          {children}

        </main>

        <footer className="flex w-full flex-wrap container">
          <div className="w-[30%]">
            <h3 className="text-[36px] font-bold">
              KOMPUNITY
            </h3>
            <h4 className="text-[22px] font-semibold">
              ООО "KompUnity" - это динамично развивающаяся компания, созданная успешными профессионалами в сфере оптовых продаж компьютерной и офисной техники.
            </h4>
          </div>
          <div className="w-[30%] text-center">
            <h3 className="text-[40px] font-semibold">
              Адрес
            </h3>
            <ul className="font-medium">
              <li>
                <a href="https://yandex.by/maps/org/kompyuniti/116356714415/?ll=27.516313%2C53.923238&z=17">
                  Сапёров 5, Минск
                </a>
              </li>
            </ul>
            <ul className="font-medium">
              <li>
                <a href="mailto:kompunity.by@gmail.com">
                  kompunity.by@gmail.com
                </a>
              </li>
            </ul>
          </div>
          <div className="w-[30%] text-center">
            <h3 className="text-[40px] font-semibold">Контакты</h3>
            <ul className="font-medium">
              <div>
                <li>А1 44 703 97 07</li>
                <li>МТС 33 636 97 07</li>
                <li>Гор 17 307 97 07</li>
              </div>
            </ul>
          </div>
          <div className="w-full text-center">
            <span>
              OOO “КомпЮнити” Адрес: г. Минск, 220035, ул. Сапёров, д. 5-1, пом. 204 Банковские реквизиты: р/с BY 14 PJCB 3012 0747041000000 933 (BYN) ОАО “Приорбанк” г. Минск, БИК PJCBBY2X УНП 193633364 На основании Устава
            </span>
          </div>
        </footer>
      </body>
    </html>
  );
}
